import { FormEvent, useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Crown, Dices, LogIn, LogOut, Play, Trophy, Users } from "lucide-react";
import { io, Socket } from "socket.io-client";
import { CONDITION_LABELS, RoomState, WinningCondition, Winner } from "@tambola/shared";
import "./exit.css";

const fallbackServerUrl = `${window.location.protocol}//${window.location.hostname}:3001`;
const socket: Socket = io(import.meta.env.VITE_SERVER_URL ?? fallbackServerUrl, { autoConnect: true });
const defaultConditions: WinningCondition[] = ["earlyFive", "topLine", "middleLine", "bottomLine", "fourCorners", "fullHouse"];
type View = "home" | "create" | "join" | "room";

export default function App() {
  const [view, setView] = useState<View>("home"), [room, setRoom] = useState<RoomState | null>(null), [roomCode, setRoomCode] = useState(""), [message, setMessage] = useState(""), [winner, setWinner] = useState<Winner | null>(null);
  useEffect(() => { const resume = () => { const saved = localStorage.getItem("tambola-session"); if (saved) { try { const session = JSON.parse(saved); if (session.roomId) socket.emit("room:reconnect", { resumeToken: session.resumeToken }); } catch { localStorage.removeItem("tambola-session"); } } }; const onState = (nextRoom: RoomState) => { setRoom(nextRoom); setRoomCode(nextRoom.id); setView("room"); }; socket.on("connect", resume); socket.on("room:state", onState); socket.on("room:created", (id: string) => { const saved = JSON.parse(localStorage.getItem("tambola-session") ?? "{}"); localStorage.setItem("tambola-session", JSON.stringify({ ...saved, roomId: id })); setRoomCode(id); setView("room"); }); socket.on("app:error", setMessage); socket.on("claim:success", setWinner); if (socket.connected) resume(); return () => { socket.off("connect", resume); socket.off("room:state", onState); socket.off("room:created"); socket.off("app:error"); socket.off("claim:success"); }; }, []);
  const exitRoom = () => { if (!window.confirm("Are you sure you want to exit this game?")) return; localStorage.removeItem("tambola-session"); socket.disconnect(); setRoom(null); setRoomCode(""); setWinner(null); setMessage(""); setView("home"); };
  if (view === "home") return <Home onCreate={() => setView("create")} onJoin={() => setView("join")} />;
  if (view === "create") return <Create onBack={() => setView("home")} onSubmit={(payload) => { const resumeToken = crypto.randomUUID(); localStorage.setItem("tambola-session", JSON.stringify({ roomId: "", nickname: payload.nickname, resumeToken })); socket.connect(); socket.emit("room:create", { ...payload, resumeToken }); }} />;
  if (view === "join") return <Join onBack={() => setView("home")} onSubmit={(payload) => { const resumeToken = crypto.randomUUID(); localStorage.setItem("tambola-session", JSON.stringify({ roomId: payload.roomId.toUpperCase(), nickname: payload.nickname, resumeToken })); socket.connect(); setRoomCode(payload.roomId.toUpperCase()); socket.emit("room:join", { ...payload, resumeToken }); setView("room"); }} />;
  return <RoomScreen room={room} roomCode={roomCode} message={message} clearMessage={() => setMessage("")} winner={winner} closeWinner={() => setWinner(null)} onExit={exitRoom} />;
}

function Home({ onCreate, onJoin }: { onCreate: () => void; onJoin: () => void }) { return <main className="landing"><div className="orb orb-one" /><div className="orb orb-two" /><motion.section initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="hero"><p className="eyebrow">A private party game</p><h1>Tambola<br /><i>Night</i></h1><p className="lede">Your friends. Your tickets. Your lucky numbers.</p><div className="actions"><button className="primary" onClick={onCreate}><Dices /> Create game</button><button className="secondary" onClick={onJoin}><LogIn /> Join with code</button></div><p className="mini">Built for phones, perfect for the living room.</p></motion.section></main>; }
function Create({ onBack, onSubmit }: { onBack: () => void; onSubmit: (p: { nickname: string; name: string; conditions: WinningCondition[]; allowMultipleWinners: boolean }) => void }) { const [conditions, setConditions] = useState(defaultConditions); const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); onSubmit({ nickname: String(data.get("nickname")), name: String(data.get("name")), conditions, allowMultipleWinners: Boolean(data.get("multiple")) }); }; return <Page title="Set the table" subtitle="Create a private room for your crew."><form onSubmit={submit} className="form"><label>Your name<input required name="nickname" maxLength={20} placeholder="e.g. Vinay" autoFocus /></label><label>Room name<input required name="name" maxLength={30} placeholder="Friday night bingo" /></label><fieldset><legend>Winning conditions</legend>{defaultConditions.map((condition) => <label className="check" key={condition}><input type="checkbox" checked={conditions.includes(condition)} onChange={() => setConditions((current) => current.includes(condition) ? current.filter((item) => item !== condition) : [...current, condition])} />{CONDITION_LABELS[condition]}</label>)}</fieldset><label className="check"><input type="checkbox" name="multiple" /> Allow multiple winners per prize</label><button className="primary" type="submit"><Crown /> Create game</button><button className="text-button" type="button" onClick={onBack}>Back</button></form></Page>; }
function Join({ onBack, onSubmit }: { onBack: () => void; onSubmit: (p: { nickname: string; roomId: string }) => void }) { const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const data = new FormData(e.currentTarget); onSubmit({ nickname: String(data.get("nickname")), roomId: String(data.get("roomId")) }); }; return <Page title="Find your table" subtitle="Ask the host for the five-character room code."><form onSubmit={submit} className="form"><label>Your name<input required name="nickname" maxLength={20} placeholder="e.g. Rahul" autoFocus /></label><label>Room code<input required name="roomId" maxLength={5} className="code-input" placeholder="XK72P" /></label><button className="primary" type="submit"><LogIn /> Join game</button><button className="text-button" type="button" onClick={onBack}>Back</button></form></Page>; }
function Page({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <main className="simple-page"><section className="form-card"><p className="eyebrow">Tambola night</p><h2>{title}</h2><p>{subtitle}</p>{children}</section></main>; }
function RoomScreen({ room, roomCode, message, clearMessage, winner, closeWinner, onExit }: { room: RoomState | null; roomCode: string; message: string; winner: Winner | null; closeWinner: () => void; clearMessage: () => void; onExit: () => void }) { if (!room) return <main className="simple-page"><section className="form-card"><p className="eyebrow">Joining room</p><h2>{roomCode}</h2><p>Connecting you to the game...</p></section></main>; const mine = room.players.find((player) => player.id === socket.id); const host = room.hostId === socket.id; return <main className="game"><header><div><p className="eyebrow">Room {room.id}</p><h2>{room.name}</h2></div><div className="header-actions"><div className="players"><Users size={18} /> {room.players.filter((player) => player.connected).length}</div><button className="exit-button" onClick={onExit}><LogOut size={16} /> Exit</button></div></header>{message && <button className="notice" onClick={clearMessage}>{message}</button>}<AnimatePresence>{winner && <motion.div className="modal-wrap" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.section className="winner" initial={{ scale: .8, y: 20 }} animate={{ scale: 1, y: 0 }}><Trophy /><p className="eyebrow">Claim successful</p><h2>{winner.nickname}</h2><p>{CONDITION_LABELS[winner.condition]}</p><button className="primary" onClick={closeWinner}>Keep playing</button></motion.section></motion.div>}</AnimatePresence>{room.status === "lobby" ? <Lobby room={room} host={host} /> : <Game room={room} mine={mine} host={host} />}</main>; }
function Lobby({ room, host }: { room: RoomState; host: boolean }) { return <section className="lobby"><div className="room-code"><span>Share this code</span><strong>{room.id}</strong><small>Friends can join before you start.</small></div><h3><Users /> At the table</h3><div className="player-list">{room.players.map((player) => <motion.div initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} key={player.id}>{player.nickname}{player.id === room.hostId && <Crown size={15} />}</motion.div>)}</div>{host ? <button className="primary start" onClick={() => socket.emit("game:start", room.id)}><Play /> Start game</button> : <p className="waiting">Waiting for {room.players.find((p) => p.id === room.hostId)?.nickname} to start...</p>}</section>; }
function Game({ room, mine, host }: { room: RoomState; mine: RoomState["players"][number] | undefined; host: boolean }) {
  const called = new Set(room.calledNumbers);
  const caller = room.players.find((player) => player.id === room.currentCallerId);
  const canCall = room.status === "playing" && (room.callingMode === "host" ? host : room.currentCallerId === socket.id);
  const callerText = room.callingMode === "host" ? "Host controls the draw" : `${caller?.nickname ?? "A player"}'s turn to draw`;
  return <section className="game-grid"><div className="draw-card"><p className="eyebrow">Last number</p><motion.div key={room.currentNumber} initial={{ scale: .5, rotate: -15 }} animate={{ scale: 1, rotate: 0 }} className="ball">{room.currentNumber ?? "?"}</motion.div><p>{room.calledNumbers.length} of 90 called</p><p className="turn-status">{callerText}</p>{canCall && <button className="primary" onClick={() => socket.emit("game:callNext", room.id)}>{room.callingMode === "turns" ? "Draw your number" : "Call next number"}</button>}{room.callingMode === "turns" && !canCall && <p className="waiting">Waiting for {caller?.nickname ?? "the next player"}...</p>}{host && <div className="mode-switch"><span>Calling mode</span><div><button className={room.callingMode === "host" ? "selected" : ""} onClick={() => socket.emit("game:setCallingMode", { roomId: room.id, mode: "host" })}>Host calls</button><button className={room.callingMode === "turns" ? "selected" : ""} onClick={() => socket.emit("game:setCallingMode", { roomId: room.id, mode: "turns" })}>Player turns</button></div></div>}</div>{mine && <div className="ticket-wrap"><h3>Your ticket</h3><div className="ticket">{mine.ticket.flatMap((row, r) => row.map((number, c) => <button key={`${r}-${c}`} disabled={number === null || !called.has(number)} className={`cell ${number && called.has(number) ? "called" : ""}`}>{number ?? ""}</button>))}</div></div>}<div className="claims"><h3><Trophy /> Claim a win</h3>{room.winningConditions.map((condition) => <button key={condition} disabled={room.winners.some((winner) => winner.condition === condition) && !room.allowMultipleWinners} onClick={() => socket.emit("claim:submit", { roomId: room.id, condition })}>{CONDITION_LABELS[condition]}{room.winners.find((winner) => winner.condition === condition) && <span>Won</span>}</button>)}</div><div className="board"><h3>Number board</h3><div>{Array.from({ length: 90 }, (_, index) => index + 1).map((number) => <span key={number} className={called.has(number) ? (number === room.currentNumber ? "current" : "marked") : ""}>{number}</span>)}</div></div></section>;
}
