import type { CallingMode, RoomState, WinningCondition } from "@tambola/shared";
import { generateTicket } from "../game/ticket.js";
import { isWinningTicket } from "../game/validation.js";
const code = () => Math.random().toString(36).slice(2, 7).toUpperCase();
export class RoomManager {
  private rooms = new Map<string, RoomState>();
  private resumeTokens = new Map<string, { roomId: string; playerId: string }>();
  create(hostId: string, resumeToken: string, nickname: string, name: string, winningConditions: WinningCondition[], allowMultipleWinners: boolean) { let id = code(); while (this.rooms.has(id)) id = code(); const room: RoomState = { id, name, hostId, status: "lobby", players: [{ id: hostId, nickname, ticket: generateTicket(), connected: true }], calledNumbers: [], currentNumber: null, callingMode: "host", currentCallerId: hostId, winningConditions, winners: [], allowMultipleWinners }; this.rooms.set(id, room); this.resumeTokens.set(resumeToken, { roomId: id, playerId: hostId }); return room; }
  get(id: string) { return this.rooms.get(id); }
  join(id: string, playerId: string, resumeToken: string, nickname: string) { const room = this.rooms.get(id); if (!room) throw new Error("Room not found. Check the code and try again."); if (room.status !== "lobby") throw new Error("This game has already started."); if (room.players.length >= 30) throw new Error("This room has reached its player limit."); if (room.players.some((player) => player.nickname.toLowerCase() === nickname.toLowerCase())) throw new Error("That nickname is already being used."); room.players.push({ id: playerId, nickname, ticket: generateTicket(), connected: true }); this.resumeTokens.set(resumeToken, { roomId: id, playerId }); return room; }
  disconnect(playerId: string) { for (const room of this.rooms.values()) { const player = room.players.find((item) => item.id === playerId); if (player) { player.connected = false; return room; } } }
  reconnect(playerId: string, resumeToken: string) { const session = this.resumeTokens.get(resumeToken); const room = session && this.rooms.get(session.roomId); if (!room || !session) throw new Error("We could not resume that player. Join the room again."); const player = room.players.find((item) => item.id === session.playerId); if (!player || player.connected) throw new Error("This player session is already active."); const previousId = player.id; player.id = playerId; player.connected = true; session.playerId = playerId; if (room.hostId === previousId) room.hostId = playerId; if (room.currentCallerId === previousId) room.currentCallerId = playerId; for (const winner of room.winners) if (winner.playerId === previousId) winner.playerId = playerId; return room; }
  start(room: RoomState, actor: string) { this.host(room, actor); room.status = "playing"; }
  callNext(room: RoomState, actor: string) { if (room.callingMode === "host") this.host(room, actor); else if (room.currentCallerId !== actor) throw new Error("It is not your turn to call a number."); if (room.status !== "playing") throw new Error("The game is not active."); const left = Array.from({ length: 90 }, (_, i) => i + 1).filter((n) => !room.calledNumbers.includes(n)); if (!left.length) throw new Error("All numbers have been called."); room.currentNumber = left[Math.floor(Math.random() * left.length)]; room.calledNumbers.push(room.currentNumber); if (room.callingMode === "turns") this.advanceCaller(room); }
  setCallingMode(room: RoomState, actor: string, mode: CallingMode) { this.host(room, actor); room.callingMode = mode; room.currentCallerId = mode === "host" ? room.hostId : room.players[room.calledNumbers.length % room.players.length]?.id ?? room.hostId; }
  claim(room: RoomState, playerId: string, condition: WinningCondition) { const player = room.players.find((item) => item.id === playerId); if (!player) throw new Error("Player not found."); if (!room.winningConditions.includes(condition)) throw new Error("This winning condition is disabled."); if (!room.allowMultipleWinners && room.winners.some((winner) => winner.condition === condition)) throw new Error("This prize has already been claimed."); if (!isWinningTicket(player.ticket, room.calledNumbers, condition)) throw new Error("You have not completed this pattern yet."); const winner = { playerId, nickname: player.nickname, condition }; room.winners.push(winner); if (condition === "fullHouse") room.status = "finished"; return winner; }
  private host(room: RoomState, actor: string) { if (room.hostId !== actor) throw new Error("Only the host can do that."); }
  private advanceCaller(room: RoomState) { const currentIndex = room.players.findIndex((player) => player.id === room.currentCallerId); room.currentCallerId = room.players[(currentIndex + 1) % room.players.length]?.id ?? room.hostId; }
}
