export const TAMBOLA_NICKNAMES: Record<number, string> = {
  1: "Son of a gun",
  2: "Two little ducks",
  3: "Cup of tea",
  4: "Knock at the door",
  5: "Fingers in a hand",
  6: "Chopping sticks",
  7: "Lucky seven",
  8: "One fat lady",
  9: "Doctor's time",
  10: "A big fat hen",
  11: "Two beautiful legs",
  12: "One dozen",
  13: "Unlucky for some",
  14: "Valentine's day",
  15: "Yet to be kissed",
  16: "Sweet sixteen",
  17: "Dancing queen",
  18: "Voting age",
  19: "Goodbye teens",
  20: "One score",
  21: "Key of the door",
  22: "Two little ducks",
  23: "You and me",
  24: "Two dozen",
  25: "Silver jubilee",
  26: "Republic day",
  27: "Gateway to heaven",
  28: "Duck and its mate",
  29: "Rise and shine",
  30: "Flirty thirty",
  31: "Time for fun",
  32: "Mouth full of teeth",
  33: "All the threes",
  34: "Ask for more",
  35: "Jump and jive",
  36: "Popular size",
  37: "More than eleven",
  38: "Christmas cake",
  39: "Watch your waistline",
  40: "Life begins at forty",
  41: "Life's begun",
  42: "Winnie the Pooh",
  43: "Down on your knees",
  44: "All the fours",
  45: "Halfway there",
  46: "Up to tricks",
  47: "Year of independence",
  48: "Four dozen",
  49: "Rise and shine",
  50: "Golden jubilee",
  51: "Shagun ka number",
  52: "Pack of cards",
  53: "Stuck in a tree",
  54: "Clean the floor",
  55: "All the fives",
  56: "Was she worth it",
  57: "All the beans",
  58: "Make them wait",
  59: "Just retired",
  60: "Five dozen",
  61: "Baker's bun",
  62: "Turn the screw",
  63: "Tickle me",
  64: "Red raw",
  65: "Old age pension",
  66: "Chakke pe chakka",
  67: "Made in heaven",
  68: "Saving grace",
  69: "Your place or mine",
  70: "Lucky blind",
  71: "Bang on the drum",
  72: "Six dozen",
  73: "Queen bee",
  74: "Candy store",
  75: "Diamond jubilee",
  76: "Trombones",
  77: "Two hockey sticks",
  78: "Heaven's gate",
  79: "One more time",
  80: "Gandhi's breakfast",
  81: "Corner shot",
  82: "Fat lady with a duck",
  83: "Time for tea",
  84: "Seven dozen",
  85: "Staying alive",
  86: "Between the sticks",
  87: "Torquay in Devon",
  88: "Two fat ladies",
  89: "Nearly there",
  90: "Top of the house",
};
